###
# Create a new API key
POST http://{{host}}:{{port}}/api/auth/apikey/create
Authorization: Bearer {{apikey}}
Content-Type: application/json

{
  "namespace": "pixel",
  "moderation": true,
  "allowedHosts": [
    "pixel.cliftbar.site"
  ],
  "scopes": ["admin", "account_read", "account_write", "ws_read"]
}

###
# Verify an api key
GET http://{{host}}:{{port}}/api/auth/apikey/verify?ns=test
Accept: application/json
Authorization: Bearer {{apikey}}
