POST http://{{host}}:{{port}}/api/auth/apikey/create
Content-Type: application/json

{
  "namespace": "test"
}

###
GET http://{{host}}:{{port}}/api/auth/apikey/verify?ns=test&apikey=dsc.6b967535-6f81-460f-9859-caa47740ce87
Accept: application/json